version: '3'

services:

  db:
    image: postgres:latest
    container_name: simplevault_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: simplevault
    container_name: simplevault_app1
    environment:
      GK_ADDRESS: app:8080
      GK_CERT: cert.pem
      GK_PRIVATE_KEY: privatekey.pem
      GK_DATABASE: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - "8081:8080" 
    depends_on:
      - db  

volumes:
  pgdata:
